export default {
    userName: 'User Name',
    enterUserName: 'Enter User Name',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter Phone Number',
    userType: 'User Type',
    add: 'ADD',
    userNameEmpty: 'user name is mandatory',
    phoneNumberEmpty: 'phone number is mandatory',
    contactAlreadyAdded: 'This contact number is already added.',
    familyNameEmpty: 'Kindly enter family name',
    hasNoFamily: 'No Family found for you. Kindly add a family.',
    createNew: 'Create New',
    externalInvites: 'External Invites',
    cancel: 'Cancel',
    createTask: 'Create Task',
    createRoute: 'CREATE ROUTE',
    zeloo: 'Zeloo',
    tasks: 'Tasks',
    noTaskPlanned: 'No current task planned',
    markDone: 'MARK DONE',
    ignoreForNow: 'IGNORE \nFOR NOW',
    active: 'Active',
    route: 'Route',
    noTaskAvailable: 'No task available',
    noLocationAvailable: 'No location available',
    pause: 'PAUSE',
    stopRoute: 'STOP ROUTE',
    folder: 'Folder',
    browseTasksInFolders: 'Browse tasks in each folders',
    premiumVersion: 'Get Premium Version for Advanced Settings',
    selectCalendar: 'Select Calendar',
    termsConditions: 'Terms & Conditions',
    aboutUs: 'About Us',
    profile: 'Profile',
    reportBug: 'Report Bug',
    settings: 'Settings',
    logout: 'Logout',
    routeName: 'Route Name',
    name: 'Name',
    numberOfEvents: 'No. of Events',
    markActive: 'Mark Active',
    delete: 'Delete',
    selectOption: 'Please select an Option',
    firstName: 'FIRST NAME',
    familyName: 'FAMILY NAME',
    sureEditFolder: 'Are you sure? do you want to edit folder image',
    editFolder: 'Edit folder Image',
    renameFolder: 'Rename Folder',
    deleteFolder: 'Delete Folder',
    chooseIcon: 'Choose icon for folder',
    takePhoto: 'Take photo',
    chooseFromLibrary: 'Choose form Library',
    noTaskFound: 'No task found on this date',
}
