export default {
    userName: 'User Name',
    enterUserName: 'Enter User Name',
    phoneNumber: 'Phone Number',
    enterPhoneNumber: 'Enter Phone Number',
    userType: 'User Type',
    add: 'ADD',
    userNameEmpty: 'user name is mandatory',
    phoneNumberEmpty: 'phone number is mandatory',
    contactAlreadyAdded: 'This contact number is already added.',
    familyNameEmpty: 'Kindly enter family name',
    hasNoFamily: 'No Family found for you. Kindly add a family.',
    createNew: 'Create New',
    externalInvites: 'External Invites',
    cancel: 'Cancel',
    createTask: 'Create Task',
    createRoute: 'Create Route',
    zeloo: 'Zeloo',
    tasks: 'Tasks',
    noTaskPlanned: 'No current task planned',
    markDone: 'MARK DONE',
    ignoreForNow: 'IGNORE \nFOR NOW',
    active: 'Active',
    route: 'Route',
    noTaskAvailable: 'No task available',
    noLocationAvailable: 'No location available',
    pause: 'PAUSE',
    stopRoute: 'STOP ROUTE',
    folder: 'Folder',
    browseTasksInFolders: 'Browse tasks in each folders'
}
