# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zeloo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Zeloo

  inherit! :search_paths
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'cxxreact',
    #'jschelpers',
    'RCTAnimation',
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTBlob',
    'RCTPushNotification', # Needed if using push notification
    'RCTActionSheet', # Needed for specific use cases
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket', # Needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'ReactNativeOpenSettings', :path => '../node_modules/react-native-open-settings'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'


  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
